// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6lsKHTA-Rn6aJREauD172lQ_bd-ix1uk',
    appId: '1:892621779554:web:070f0db60423f29a62573b',
    messagingSenderId: '892621779554',
    projectId: 'doorstep-96389',
    authDomain: 'doorstep-96389.firebaseapp.com',
    storageBucket: 'doorstep-96389.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkXKEc_2sTyXAQxnXO8xI9p_6SeBggNRA',
    appId: '1:892621779554:android:29c07f9a045994f562573b',
    messagingSenderId: '892621779554',
    projectId: 'doorstep-96389',
    storageBucket: 'doorstep-96389.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8cm8IuSonBUT7RiBCAZUlHGadLz_nAHs',
    appId: '1:892621779554:ios:4aa7c8ddbb54f38d62573b',
    messagingSenderId: '892621779554',
    projectId: 'doorstep-96389',
    storageBucket: 'doorstep-96389.firebasestorage.app',
    iosBundleId: 'com.example.doorstepmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8cm8IuSonBUT7RiBCAZUlHGadLz_nAHs',
    appId: '1:892621779554:ios:4aa7c8ddbb54f38d62573b',
    messagingSenderId: '892621779554',
    projectId: 'doorstep-96389',
    storageBucket: 'doorstep-96389.firebasestorage.app',
    iosBundleId: 'com.example.doorstepmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6lsKHTA-Rn6aJREauD172lQ_bd-ix1uk',
    appId: '1:892621779554:web:9c067bf0fdf2418e62573b',
    messagingSenderId: '892621779554',
    projectId: 'doorstep-96389',
    authDomain: 'doorstep-96389.firebaseapp.com',
    storageBucket: 'doorstep-96389.firebasestorage.app',
  );
}
