// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlLztcR2dXjEu7mb17lQDTBGllqKZcP-w',
    appId: '1:572521062790:web:2f6c3efae6c2788fdb4c07',
    messagingSenderId: '572521062790',
    projectId: 'doorstepmart-9c3ad',
    authDomain: 'doorstepmart-9c3ad.firebaseapp.com',
    storageBucket: 'doorstepmart-9c3ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO9ZztK3mpYE5BTfNR4pjynkULJ4ysp2E',
    appId: '1:572521062790:android:c9ef1d3b699f3649db4c07',
    messagingSenderId: '572521062790',
    projectId: 'doorstepmart-9c3ad',
    storageBucket: 'doorstepmart-9c3ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_hsLbwD37gvV8mJ1ksHZLKasp6-Nl3ew',
    appId: '1:572521062790:ios:8e622a74f749d99adb4c07',
    messagingSenderId: '572521062790',
    projectId: 'doorstepmart-9c3ad',
    storageBucket: 'doorstepmart-9c3ad.firebasestorage.app',
    iosBundleId: 'com.example.doorstepmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_hsLbwD37gvV8mJ1ksHZLKasp6-Nl3ew',
    appId: '1:572521062790:ios:8e622a74f749d99adb4c07',
    messagingSenderId: '572521062790',
    projectId: 'doorstepmart-9c3ad',
    storageBucket: 'doorstepmart-9c3ad.firebasestorage.app',
    iosBundleId: 'com.example.doorstepmart',
  );
}
